
taxi_rides_ny:
  outputs:
    dev:
      dataset: trips_data_all1
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /workspaces/data-engineering-zoomcamp-nyssa/hw_1/terraform-gcp/key.json
      location: us-east1
      method: service-account
      priority: interactive
      project: rare-sound-412302
      threads: 4
      type: bigquery
  target: dev
